package jtroop.pipeline;

import java.net.InetSocketAddress;
import java.nio.ByteBuffer;

/**
 * A single stage in a {@link Pipeline}. Layers transform inbound bytes as they
 * travel up the stack and outbound bytes as they travel down.
 *
 * <p>Every call now receives a per-connection {@link Context}. The context is
 * cheap: one packed {@code long} id, one {@link InetSocketAddress} reference,
 * and two {@code volatile long} byte counters. It is allocated once at accept
 * time and reused for the life of the connection, so the extra parameter
 * costs one additional {@code aload} in generated bytecode per layer call.
 */
public interface Layer {

    /** Encode {@code payload} → {@code out} (downstream). */
    void encodeOutbound(Context ctx, ByteBuffer payload, ByteBuffer out);

    /** Decode {@code wire} → frame (upstream). Returns {@code null} if the
     *  wire does not yet contain a complete frame, or the frame was consumed
     *  (dropped) by this layer. */
    ByteBuffer decodeInbound(Context ctx, ByteBuffer wire);

    /** Test / cold-path convenience: forwards to the Context-taking overload
     *  with a shared no-op Context. NOT used by the fused hot path. */
    default void encodeOutbound(ByteBuffer payload, ByteBuffer out) {
        encodeOutbound(LayerContext.NOOP, payload, out);
    }

    /** Test / cold-path convenience: see {@link #encodeOutbound(ByteBuffer, ByteBuffer)}. */
    default ByteBuffer decodeInbound(ByteBuffer wire) {
        return decodeInbound(LayerContext.NOOP, wire);
    }

    /**
     * Connection lifecycle callback invoked once when a connection closes
     * (normal shutdown, handshake rejection, peer reset, timeout). Cold
     * path — fires at most once per connection, not per message.
     *
     * <p>Use this to release any per-connection state a layer keeps in its
     * own data structures. The default is a no-op; stateful layers such as
     * {@code AllowListLayer}, {@code RateLimitLayer}, {@code AckLayer},
     * {@code DuplicateFilterLayer} and {@code SequencingLayer} override it
     * to evict their per-connection entries so long-lived servers don't
     * accumulate memory proportional to total connections ever seen.
     *
     * <p>Invoked by {@link Pipeline#onConnectionClose(long)} which the
     * {@code Server} / {@code Client} call on every close path. Safe to
     * call from any thread; layers must perform their own synchronisation
     * if they share state with the hot encode/decode path.
     *
     * @param connectionId packed {@code ConnectionId} of the closing
     *                     connection — same value as
     *                     {@link Context#connectionId()} previously saw
     *                     on encode/decode calls for this connection.
     */
    default void onConnectionClose(long connectionId) {
        // no-op by default
    }

    /**
     * Per-connection view exposed to every layer call. Immutable accessors;
     * mutating methods ({@link #closeAfterFlush}, {@link #closeNow}) schedule
     * the action on the owning {@code EventLoop}.
     */
    interface Context {
        /** Packed (generation &lt;&lt; 32 | index) — same layout as
         *  {@code jtroop.session.ConnectionId}. */
        long connectionId();

        /** Peer address. For UDP unconnected, the address of the datagram
         *  we're currently processing. */
        InetSocketAddress remoteAddress();

        /** Cumulative bytes read off the wire on this connection. Updated
         *  BEFORE the pipeline sees them. */
        long bytesRead();

        /** Cumulative bytes written to the wire on this connection. */
        long bytesWritten();

        /** {@code System.nanoTime()} snapshot at connection accept /
         *  client connect. */
        long connectedAtNanos();

        /** Schedule graceful close: current frame flushes, then channel
         *  closes. Safe to call from any thread; the server/client enqueues
         *  to the owning loop. */
        void closeAfterFlush();

        /** Immediate abrupt close. Safe to call from any thread. */
        void closeNow();
    }
}
