package jtroop.codec;

import jtroop.core.BufferCharSequence;
import jtroop.core.ReadBuffer;
import jtroop.core.WriteBuffer;
import jtroop.generate.CodecClassGenerator;
import org.junit.jupiter.api.Test;

import java.nio.ByteBuffer;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Edge-case codec tests: empty records, single fields, many fields,
 * nested records, CharSequence round-trip, byte[] fields, multi-string.
 */
class CodecEdgeCaseTest {

    // 1. Empty record
    public record Empty() {}

    // 2. Single boolean field
    public record Flag(boolean on) {}

    // 3. Many fields (8 — mixed types)
    public record Big(int a, int b, int c, int d, long e, float f, double g, boolean h) {}

    // 4. Nested record
    public record Inner(int x) {}
    public record Wrapper(Inner inner) {}

    // 5. CharSequence field
    public record Msg(CharSequence text) {}

    // 6. byte[] field
    public record Blob(byte[] data) {}

    // 7. Multiple String/CharSequence fields
    public record Multi(CharSequence a, CharSequence b, int c) {}

    // 8. Single long field
    public record Single(long id) {}

    // 9. Boolean-first (boolean not last field — stress-test bytecode stack)
    public record BoolFirst(boolean flag, int value) {}

    // ── helpers ──────────────────────────────────────────────────────

    private Record roundTrip(CodecRegistry reg, Record msg) {
        var buf = ByteBuffer.allocate(4096);
        reg.encode(msg, new WriteBuffer(buf));
        buf.flip();
        return reg.decode(new ReadBuffer(buf));
    }

    private int wireSize(CodecRegistry reg, Record msg) {
        var buf = ByteBuffer.allocate(4096);
        reg.encode(msg, new WriteBuffer(buf));
        return buf.position();  // includes 2-byte typeId prefix
    }

    // ── 1. Empty record ─────────────────────────────────────────────

    @Test
    void emptyRecord_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Empty.class);
        assertEquals(new Empty(), roundTrip(reg, new Empty()));
    }

    @Test
    void emptyRecord_wireSize_isTwoBytes() {
        var reg = new CodecRegistry();
        reg.register(Empty.class);
        // Only the 2-byte typeId prefix, no payload
        assertEquals(2, wireSize(reg, new Empty()));
    }

    // ── 2. Single boolean ───────────────────────────────────────────

    @Test
    void flag_generatedCodec_succeeds() {
        // Verify the generated bytecode codec works for boolean, not just the
        // reflection fallback.
        var codec = CodecClassGenerator.generate(Flag.class);
        assertNotNull(codec, "boolean record should produce a generated codec");
        var buf = ByteBuffer.allocate(64);
        codec.encode(new Flag(true), buf);
        buf.flip();
        var decoded = (Flag) codec.decode(buf);
        assertEquals(new Flag(true), decoded);
    }

    @Test
    void flag_generatedCodec_false() {
        var codec = CodecClassGenerator.generate(Flag.class);
        var buf = ByteBuffer.allocate(64);
        codec.encode(new Flag(false), buf);
        buf.flip();
        var decoded = (Flag) codec.decode(buf);
        assertEquals(new Flag(false), decoded);
    }

    @Test
    void flag_true_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Flag.class);
        assertEquals(new Flag(true), roundTrip(reg, new Flag(true)));
    }

    @Test
    void flag_false_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Flag.class);
        assertEquals(new Flag(false), roundTrip(reg, new Flag(false)));
    }

    @Test
    void flag_wireSize_isThreeBytes() {
        var reg = new CodecRegistry();
        reg.register(Flag.class);
        // 2-byte typeId + 1-byte boolean
        assertEquals(3, wireSize(reg, new Flag(true)));
    }

    // ── 3. Many fields (8, mixed types) ─────────────────────────────

    @Test
    void big_generatedCodec_succeeds() {
        var codec = CodecClassGenerator.generate(Big.class);
        assertNotNull(codec, "8-field mixed record should produce a generated codec");
        var buf = ByteBuffer.allocate(256);
        codec.encode(new Big(1, 2, 3, 4, 5L, 6.0f, 7.0, true), buf);
        buf.flip();
        var decoded = (Big) codec.decode(buf);
        assertEquals(new Big(1, 2, 3, 4, 5L, 6.0f, 7.0, true), decoded);
    }

    @Test
    void big_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Big.class);
        var msg = new Big(1, 2, 3, 4, 5L, 6.0f, 7.0, true);
        assertEquals(msg, roundTrip(reg, msg));
    }

    @Test
    void big_extremeValues_roundTrip() {
        var reg = new CodecRegistry();
        reg.register(Big.class);
        var msg = new Big(
                Integer.MIN_VALUE, Integer.MAX_VALUE, 0, -1,
                Long.MIN_VALUE, Float.NaN, Double.NEGATIVE_INFINITY, false);
        var decoded = (Big) roundTrip(reg, msg);
        assertEquals(Integer.MIN_VALUE, decoded.a());
        assertEquals(Integer.MAX_VALUE, decoded.b());
        assertEquals(0, decoded.c());
        assertEquals(-1, decoded.d());
        assertEquals(Long.MIN_VALUE, decoded.e());
        assertTrue(Float.isNaN(decoded.f()));
        assertEquals(Double.NEGATIVE_INFINITY, decoded.g());
        assertFalse(decoded.h());
    }

    @Test
    void big_wireSize() {
        var reg = new CodecRegistry();
        reg.register(Big.class);
        // 2 typeId + 4*int + 8 long + 4 float + 8 double + 1 bool = 2+16+8+4+8+1 = 39
        assertEquals(39, wireSize(reg, new Big(0, 0, 0, 0, 0L, 0f, 0.0, false)));
    }

    // ── 4. Nested record ────────────────────────────────────────────

    @Test
    void nestedRecord_failsWithUnsupportedType() {
        var reg = new CodecRegistry();
        // Nested record fields are not a supported primitive/String/CharSequence type,
        // so registration should throw.
        assertThrows(IllegalArgumentException.class, () -> reg.register(Wrapper.class));
    }

    // ── 5. CharSequence field ───────────────────────────────────────

    @Test
    void charSequence_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Msg.class);
        var decoded = (Msg) roundTrip(reg, new Msg("hello"));
        assertEquals("hello", decoded.text().toString());
    }

    @Test
    void charSequence_decodesAsBufferCharSequence() {
        var reg = new CodecRegistry();
        reg.register(Msg.class);
        var decoded = (Msg) roundTrip(reg, new Msg("test"));
        assertInstanceOf(BufferCharSequence.class, decoded.text());
    }

    @Test
    void charSequence_emptyString_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Msg.class);
        var decoded = (Msg) roundTrip(reg, new Msg(""));
        assertEquals("", decoded.text().toString());
    }

    @Test
    void charSequence_bufferCharSequence_reencodes() {
        var reg = new CodecRegistry();
        reg.register(Msg.class);
        // First round: String -> BufferCharSequence
        var first = (Msg) roundTrip(reg, new Msg("re-encode me"));
        assertInstanceOf(BufferCharSequence.class, first.text());
        // Second round: BufferCharSequence -> BufferCharSequence
        var second = (Msg) roundTrip(reg, first);
        assertEquals("re-encode me", second.text().toString());
    }

    @Test
    void charSequence_unicode_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Msg.class);
        var decoded = (Msg) roundTrip(reg, new Msg("\u00e9\u00e8\u00ea\u2603\ud83d\ude00"));
        assertEquals("\u00e9\u00e8\u00ea\u2603\ud83d\ude00", decoded.text().toString());
    }

    // ── 6. byte[] field ─────────────────────────────────────────────

    @Test
    void byteArray_failsWithUnsupportedType() {
        var reg = new CodecRegistry();
        // byte[] is not a supported component type (only byte primitive is)
        assertThrows(IllegalArgumentException.class, () -> reg.register(Blob.class));
    }

    // ── 7. Multiple String/CharSequence fields ──────────────────────

    @Test
    void multiCharSequence_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Multi.class);
        var decoded = (Multi) roundTrip(reg, new Multi("alpha", "beta", 42));
        assertEquals("alpha", decoded.a().toString());
        assertEquals("beta", decoded.b().toString());
        assertEquals(42, decoded.c());
    }

    @Test
    void multiCharSequence_emptyStrings_roundTrip() {
        var reg = new CodecRegistry();
        reg.register(Multi.class);
        var decoded = (Multi) roundTrip(reg, new Multi("", "", 0));
        assertEquals("", decoded.a().toString());
        assertEquals("", decoded.b().toString());
        assertEquals(0, decoded.c());
    }

    @Test
    void multiCharSequence_reencodes() {
        var reg = new CodecRegistry();
        reg.register(Multi.class);
        var first = (Multi) roundTrip(reg, new Multi("one", "two", 99));
        // Both fields are now BufferCharSequence; re-encode them
        var second = (Multi) roundTrip(reg, first);
        assertEquals("one", second.a().toString());
        assertEquals("two", second.b().toString());
        assertEquals(99, second.c());
    }

    // ── 8. Single long field ────────────────────────────────────────

    @Test
    void singleLong_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(Single.class);
        assertEquals(new Single(42L), roundTrip(reg, new Single(42L)));
    }

    @Test
    void singleLong_extremeValues() {
        var reg = new CodecRegistry();
        reg.register(Single.class);
        assertEquals(new Single(Long.MAX_VALUE), roundTrip(reg, new Single(Long.MAX_VALUE)));
        assertEquals(new Single(Long.MIN_VALUE), roundTrip(reg, new Single(Long.MIN_VALUE)));
        assertEquals(new Single(0L), roundTrip(reg, new Single(0L)));
    }

    @Test
    void singleLong_wireSize() {
        var reg = new CodecRegistry();
        reg.register(Single.class);
        // 2 typeId + 8 long = 10
        assertEquals(10, wireSize(reg, new Single(0L)));
    }

    // ── 9. Boolean-first: boolean not last field ────────────────────

    @Test
    void boolFirst_generatedCodec_roundTrips() {
        // If boolean encoding leaves garbage on the stack, the subsequent
        // int field encode will fail verification or produce wrong output.
        var codec = CodecClassGenerator.generate(BoolFirst.class);
        assertNotNull(codec);
        var buf = ByteBuffer.allocate(64);
        codec.encode(new BoolFirst(true, 42), buf);
        buf.flip();
        var decoded = (BoolFirst) codec.decode(buf);
        assertEquals(new BoolFirst(true, 42), decoded);
    }

    @Test
    void boolFirst_false_roundTrips() {
        var reg = new CodecRegistry();
        reg.register(BoolFirst.class);
        assertEquals(new BoolFirst(false, 99), roundTrip(reg, new BoolFirst(false, 99)));
    }

    // ── Verify generated codec is actually used (not silently falling back) ──

    @Test
    void generatedCodec_isUsedForPrimitiveRecords() {
        var reg = new CodecRegistry();
        reg.register(Flag.class);
        reg.register(Big.class);
        reg.register(Single.class);
        reg.register(BoolFirst.class);
        reg.register(Empty.class);

        assertNotNull(reg.generatedCodecFor(Flag.class), "Flag should use generated codec");
        assertNotNull(reg.generatedCodecFor(Big.class), "Big should use generated codec");
        assertNotNull(reg.generatedCodecFor(Single.class), "Single should use generated codec");
        assertNotNull(reg.generatedCodecFor(BoolFirst.class), "BoolFirst should use generated codec");
        assertNotNull(reg.generatedCodecFor(Empty.class), "Empty should use generated codec");
    }
}
