package jtroop.pipeline;

import jtroop.generate.FusedPipelineGenerator;
import jtroop.pipeline.layers.CompressionLayer;
import jtroop.pipeline.layers.EncryptionLayer;
import jtroop.pipeline.layers.FramingLayer;
import org.junit.jupiter.api.Test;

import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import java.nio.ByteBuffer;
import java.security.NoSuchAlgorithmException;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Edge-case tests for {@link Pipeline} and {@link FusedPipelineGenerator}.
 *
 * <p>Covers: empty pipeline, single layer fused generation, many layers (12),
 * mutation on empty pipeline, stateful layer isolation, replace with missing
 * type, shape cache sharing, zero-length payload encode, and empty ByteBuffer
 * decode.
 */
class PipelineEdgeCaseTest {

    // ------------------------------------------------------------------
    // 1. Empty pipeline (zero layers) — passthrough
    // ------------------------------------------------------------------

    @Test
    void emptyPipeline_encodeOutbound_passesThrough() {
        var pipeline = new Pipeline();
        var payload = ByteBuffer.allocate(16);
        payload.putInt(42);
        payload.flip();

        var wire = ByteBuffer.allocate(64);
        pipeline.encodeOutbound(payload, wire);
        wire.flip();

        assertEquals(42, wire.getInt());
    }

    @Test
    void emptyPipeline_decodeInbound_passesThrough() {
        var pipeline = new Pipeline();
        var wire = ByteBuffer.allocate(16);
        wire.putInt(99);
        wire.flip();

        var decoded = pipeline.decodeInbound(wire);
        assertNotNull(decoded);
        assertSame(wire, decoded, "empty pipeline decode should return the same buffer");
        assertEquals(99, decoded.getInt());
    }

    @Test
    void emptyPipeline_fused_passesThrough() {
        var pipeline = new Pipeline();
        var fused = pipeline.fused();
        assertNotNull(fused);

        var payload = ByteBuffer.allocate(16);
        payload.putInt(77);
        payload.flip();

        var wire = ByteBuffer.allocate(64);
        fused.encodeOutbound(payload, wire);
        wire.flip();
        assertEquals(77, wire.getInt());
    }

    @Test
    void emptyPipeline_fused_decodeReturnsWire() {
        var pipeline = new Pipeline();
        var wire = ByteBuffer.allocate(16);
        wire.putInt(55);
        wire.flip();

        var decoded = pipeline.fused().decodeInbound(wire);
        assertNotNull(decoded);
        assertEquals(55, decoded.getInt());
    }

    @Test
    void emptyPipeline_sizeIsZero() {
        var pipeline = new Pipeline();
        assertEquals(0, pipeline.size());
        assertEquals(0, pipeline.layers().length);
    }

    // ------------------------------------------------------------------
    // 2. Single layer — fused class generation
    // ------------------------------------------------------------------

    @Test
    void singleLayer_fusedIsHiddenClass() {
        var pipeline = new Pipeline(new FramingLayer());
        var fused = pipeline.fused();
        assertTrue(fused.getClass().isHidden(),
                "single-layer fused pipeline must be a hidden class");
    }

    @Test
    void singleLayer_fusedRoundtrip() {
        var pipeline = new Pipeline(new FramingLayer());
        var fused = pipeline.fused();

        var payload = ByteBuffer.allocate(32);
        payload.putInt(123);
        payload.putInt(456);
        payload.flip();

        var wire = ByteBuffer.allocate(128);
        fused.encodeOutbound(payload, wire);
        wire.flip();

        var decoded = fused.decodeInbound(wire);
        assertNotNull(decoded);
        assertEquals(123, decoded.getInt());
        assertEquals(456, decoded.getInt());
    }

    // ------------------------------------------------------------------
    // 3. Many layers (12) — fused generator handles it
    // ------------------------------------------------------------------

    /** A trivial passthrough layer for stacking tests. Must be public so the
     *  hidden class generated by FusedPipelineGenerator can invokevirtual on it. */
    public static final class PassthroughLayer implements Layer {
        @Override
        public void encodeOutbound(Context ctx, ByteBuffer payload, ByteBuffer out) {
            out.put(payload);
        }

        @Override
        public ByteBuffer decodeInbound(Context ctx, ByteBuffer wire) {
            return wire;
        }
    }

    @Test
    void manyLayers_12_fusedRoundtrip() {
        // 12 passthrough layers should all be fused into a single hidden class
        var layers = new Layer[12];
        for (int i = 0; i < 12; i++) layers[i] = new PassthroughLayer();
        var pipeline = new Pipeline(layers);

        assertEquals(12, pipeline.size());
        assertTrue(pipeline.fused().getClass().isHidden());

        var payload = ByteBuffer.allocate(32);
        payload.putInt(0xCAFEBABE);
        payload.flip();

        var wire = ByteBuffer.allocate(128);
        pipeline.fused().encodeOutbound(payload, wire);
        wire.flip();

        var decoded = pipeline.fused().decodeInbound(wire);
        assertNotNull(decoded);
        assertEquals(0xCAFEBABE, decoded.getInt());
    }

    @Test
    void manyLayers_plainPipelineRoundtrip() {
        var layers = new Layer[12];
        for (int i = 0; i < 12; i++) layers[i] = new PassthroughLayer();
        var pipeline = new Pipeline(layers);

        var payload = ByteBuffer.allocate(32);
        payload.putInt(0xDEAD);
        payload.flip();

        var wire = ByteBuffer.allocate(128);
        pipeline.encodeOutbound(payload, wire);
        wire.flip();

        var decoded = pipeline.decodeInbound(wire);
        assertNotNull(decoded);
        assertEquals(0xDEAD, decoded.getInt());
    }

    @Test
    void manyLayers_mixedTypes_fusedRoundtrip() {
        // Mix of real layers: framing at bottom, compression in middle,
        // passthrough padding to 10+
        var layers = new Layer[10];
        layers[0] = new CompressionLayer();
        layers[1] = new FramingLayer();
        for (int i = 2; i < 10; i++) layers[i] = new PassthroughLayer();
        // Note: CompressionLayer first (encode direction), FramingLayer second
        // On decode: passthrough layers first (no-op), then framing, then decompression
        // This works because passthrough layers don't alter the data.
        // But FramingLayer needs proper framing on decode, so let's reorder:
        // encode order: passthrough..., compression, framing (framing is outermost = last in encode)
        // Actually, let's just use all passthrough + framing at the end
        var layers2 = new Layer[10];
        for (int i = 0; i < 9; i++) layers2[i] = new PassthroughLayer();
        layers2[9] = new FramingLayer();
        var pipeline = new Pipeline(layers2);

        var payload = ByteBuffer.allocate(32);
        payload.putInt(42);
        payload.flip();

        var wire = ByteBuffer.allocate(256);
        pipeline.fused().encodeOutbound(payload, wire);
        wire.flip();

        var decoded = pipeline.fused().decodeInbound(wire);
        assertNotNull(decoded);
        assertEquals(42, decoded.getInt());
    }

    // ------------------------------------------------------------------
    // 4. Pipeline mutation on empty pipeline
    // ------------------------------------------------------------------

    @Test
    void emptyPipeline_addFirst() {
        var empty = new Pipeline();
        var withLayer = empty.addFirst(new FramingLayer());
        assertEquals(0, empty.size());
        assertEquals(1, withLayer.size());
        assertEquals(FramingLayer.class, withLayer.layers()[0].getClass());
    }

    @Test
    void emptyPipeline_addLast() {
        var empty = new Pipeline();
        var withLayer = empty.addLast(new FramingLayer());
        assertEquals(1, withLayer.size());
        assertEquals(FramingLayer.class, withLayer.layers()[0].getClass());
    }

    @Test
    void emptyPipeline_removeReturnsUnchanged() {
        var empty = new Pipeline();
        var result = empty.remove(FramingLayer.class);
        assertSame(empty, result, "removing from empty pipeline should return same instance");
    }

    @Test
    void emptyPipeline_replaceThrows() {
        var empty = new Pipeline();
        assertThrows(IllegalArgumentException.class,
                () -> empty.replace(FramingLayer.class, new FramingLayer()),
                "replacing in empty pipeline should throw");
    }

    // ------------------------------------------------------------------
    // 5. Only stateful layers — fresh instances per connection
    // ------------------------------------------------------------------

    @Test
    void statefulLayers_freshInstancesAreIndependent() throws NoSuchAlgorithmException {
        var keyGen = KeyGenerator.getInstance("AES");
        keyGen.init(128);
        SecretKey key = keyGen.generateKey();

        // Two separate pipelines with their own FramingLayer + EncryptionLayer
        // simulate two connections each getting fresh layer instances.
        var framing1 = new FramingLayer();
        var enc1 = new EncryptionLayer(key);
        var pipeline1 = new Pipeline(enc1, framing1);

        var framing2 = new FramingLayer();
        var enc2 = new EncryptionLayer(key);
        var pipeline2 = new Pipeline(enc2, framing2);

        // Encode on pipeline1
        var payload1 = ByteBuffer.allocate(32);
        payload1.putInt(111);
        payload1.flip();
        var wire1 = ByteBuffer.allocate(256);
        pipeline1.encodeOutbound(payload1, wire1);
        wire1.flip();

        // Encode on pipeline2
        var payload2 = ByteBuffer.allocate(32);
        payload2.putInt(222);
        payload2.flip();
        var wire2 = ByteBuffer.allocate(256);
        pipeline2.encodeOutbound(payload2, wire2);
        wire2.flip();

        // Each decodes its own wire — independent state
        var decoded1 = pipeline1.decodeInbound(wire1);
        assertNotNull(decoded1);
        assertEquals(111, decoded1.getInt());

        var decoded2 = pipeline2.decodeInbound(wire2);
        assertNotNull(decoded2);
        assertEquals(222, decoded2.getInt());
    }

    @Test
    void statefulLayers_fusedSharesHiddenClass() throws NoSuchAlgorithmException {
        var keyGen = KeyGenerator.getInstance("AES");
        keyGen.init(128);
        SecretKey key = keyGen.generateKey();

        // Same shape (EncryptionLayer, FramingLayer) but different instances
        var p1 = new Pipeline(new EncryptionLayer(key), new FramingLayer());
        var p2 = new Pipeline(new EncryptionLayer(key), new FramingLayer());

        assertSame(p1.fused().getClass(), p2.fused().getClass(),
                "same shape with different layer instances should share hidden class");
    }

    // ------------------------------------------------------------------
    // 6. Pipeline.replace with non-existent type
    // ------------------------------------------------------------------

    @Test
    void replace_nonExistentType_throwsWithClearMessage() {
        var pipeline = new Pipeline(new FramingLayer());
        var ex = assertThrows(IllegalArgumentException.class,
                () -> pipeline.replace(CompressionLayer.class, new CompressionLayer()));
        assertTrue(ex.getMessage().contains("CompressionLayer"),
                "error message should name the missing layer type");
    }

    // ------------------------------------------------------------------
    // 7. Shape cache — same shape from different Pipeline instances
    // ------------------------------------------------------------------

    @Test
    void shapeCache_samePipelineShape_sharesFusedClass() {
        long hitsBefore = FusedPipelineGenerator.cacheHits();

        var p1 = new Pipeline(new PassthroughLayer());
        var p2 = new Pipeline(new PassthroughLayer());

        assertSame(p1.fused().getClass(), p2.fused().getClass(),
                "same shape from different Pipeline instances must share hidden class");
        assertTrue(FusedPipelineGenerator.cacheHits() > hitsBefore,
                "second identical-shape pipeline must produce a cache hit");
    }

    @Test
    void shapeCache_differentShapes_differentClasses() {
        var p1 = new Pipeline(new PassthroughLayer());
        var p2 = new Pipeline(new PassthroughLayer(), new PassthroughLayer());

        assertNotSame(p1.fused().getClass(), p2.fused().getClass(),
                "different shapes must produce different hidden classes");
    }

    // ------------------------------------------------------------------
    // 8. Encode zero-length payload
    // ------------------------------------------------------------------

    @Test
    void zeroLengthPayload_plainPipeline_encode() {
        var pipeline = new Pipeline(new FramingLayer());
        var payload = ByteBuffer.allocate(0);
        // payload has 0 remaining

        var wire = ByteBuffer.allocate(64);
        pipeline.encodeOutbound(payload, wire);
        wire.flip();

        // FramingLayer prepends length=0
        assertEquals(4, wire.remaining(), "wire should contain only the 4-byte length prefix");
        assertEquals(0, wire.getInt(), "length prefix should be 0 for empty payload");
    }

    @Test
    void zeroLengthPayload_fusedPipeline_encode() {
        var pipeline = new Pipeline(new FramingLayer());
        var payload = ByteBuffer.allocate(0);

        var wire = ByteBuffer.allocate(64);
        pipeline.fused().encodeOutbound(payload, wire);
        wire.flip();

        assertEquals(4, wire.remaining());
        assertEquals(0, wire.getInt());
    }

    @Test
    void zeroLengthPayload_emptyPipeline_encode() {
        var pipeline = new Pipeline();
        var payload = ByteBuffer.allocate(0);

        var wire = ByteBuffer.allocate(64);
        pipeline.encodeOutbound(payload, wire);
        wire.flip();

        assertEquals(0, wire.remaining(), "empty payload through empty pipeline = 0 bytes");
    }

    @Test
    void zeroLengthPayload_roundtrip_throughFraming() {
        var pipeline = new Pipeline(new FramingLayer());

        var payload = ByteBuffer.allocate(0);
        var wire = ByteBuffer.allocate(64);
        pipeline.encodeOutbound(payload, wire);
        wire.flip();

        var decoded = pipeline.decodeInbound(wire);
        assertNotNull(decoded);
        assertEquals(0, decoded.remaining(), "round-tripped empty payload should be empty");
    }

    // ------------------------------------------------------------------
    // 9. Decode empty ByteBuffer (position == limit)
    // ------------------------------------------------------------------

    @Test
    void emptyByteBuffer_decode_framingReturnsNull() {
        var pipeline = new Pipeline(new FramingLayer());
        var emptyWire = ByteBuffer.allocate(0);

        var decoded = pipeline.decodeInbound(emptyWire);
        assertNull(decoded, "framing layer should return null for empty wire");
    }

    @Test
    void emptyByteBuffer_decode_fusedFramingReturnsNull() {
        var pipeline = new Pipeline(new FramingLayer());
        var emptyWire = ByteBuffer.allocate(0);

        var decoded = pipeline.fused().decodeInbound(emptyWire);
        assertNull(decoded, "fused framing layer should return null for empty wire");
    }

    @Test
    void emptyByteBuffer_decode_emptyPipelineReturnsBuffer() {
        var pipeline = new Pipeline();
        var emptyWire = ByteBuffer.allocate(0);

        var decoded = pipeline.decodeInbound(emptyWire);
        assertNotNull(decoded, "empty pipeline should return the buffer as-is");
        assertEquals(0, decoded.remaining());
    }

    @Test
    void emptyByteBuffer_decode_fusedEmptyPipelineReturnsBuffer() {
        var pipeline = new Pipeline();
        var emptyWire = ByteBuffer.allocate(0);

        var decoded = pipeline.fused().decodeInbound(emptyWire);
        assertNotNull(decoded, "fused empty pipeline should return the buffer as-is");
        assertEquals(0, decoded.remaining());
    }

    @Test
    void positionEqualsLimit_decode_framingReturnsNull() {
        // Buffer has capacity but position == limit (nothing to read)
        var wire = ByteBuffer.allocate(64);
        wire.flip(); // position=0, limit=0

        var pipeline = new Pipeline(new FramingLayer());
        var decoded = pipeline.decodeInbound(wire);
        assertNull(decoded);
    }
}
